### ISSUE TITLE
Double shortmess options, should have one?

### ISSUE THREAD

**Issue by tuyenpm9** [itchyny/dotfiles#4]
https://github.com/itchyny/dotfiles/blob/4323e3cd8a0c0355ea76dea2bfe578c975526ed4/.vimrc#L18
https://github.com/itchyny/dotfiles/blob/4323e3cd8a0c0355ea76dea2bfe578c975526ed4/.vimrc#L56

**Comment by itchyny** [comment]
It works as expected because it uses `+=` operator. I think I wrote in separated form on purpose.
