### ISSUE TITLE
No different between yie and yy

### ISSUE THREAD

**Issue by tuyenpm9** [itchyny/dotfiles#5]
https://github.com/itchyny/dotfiles/blob/4323e3cd8a0c0355ea76dea2bfe578c975526ed4/.vimrc#L117

Shoud we use default instead of map yie?

**Comment by itchyny** [comment]
It yanks all the lines in the buffer so it is different from yy which yanks the current line.

**Comment by tuyenpm9** [comment]
Nice, I'll find it later.
