### ISSUE TITLE
[Question] Is there a way to manage plugins options without Miv?

### ISSUE THREAD

**Issue by tuyenpm9** [itchyny/dotfiles#6]
If not I have to learn haskell to manage it. It's kind of struggle to keep vimrc clean without third software/plugins. Maybe a VimL function that parse yaml file?

**Comment by itchyny** [comment]
This is my dotfiles repository and I use miv so I configure using miv. Basically you should not clone other dotfiles repo and use is directly. You can create your own dotfiles repository and use any other Vim plugin managers freely.
